version: '3'

services:
  app:
    build:
      context: .
      args:
        UID: $UID
    container_name: the-grads-backend
    image: the-grads-backend
    command: make run-dev
    volumes:
      - static-data:/vol/web
      - .:/home/python/app
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    container_name: the-grads-db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
      name: "the-grads-db"
  static-data:


