"""empty message

Revision ID: 7a9ae6c9ea45
Revises: a11eb0b2f785
Create Date: 2023-10-20 02:36:54.286606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9ae6c9ea45'
down_revision = 'a11eb0b2f785'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_data', sa.Column('power_delivery_ac', sa.Float(), nullable=True))
    op.add_column('power_data', sa.Column('power_delivery_dc', sa.Float(), nullable=True))
    op.drop_column('power_data', 'power_delivery')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_data', sa.Column('power_delivery', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('power_data', 'power_delivery_dc')
    op.drop_column('power_data', 'power_delivery_ac')
    # ### end Alembic commands ###
