"""empty message

Revision ID: a11eb0b2f785
Revises: 7771c94c4005
Create Date: 2023-07-30 14:18:45.942256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11eb0b2f785'
down_revision = '7771c94c4005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_data', sa.Column('event_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('power_data', 'event_date')
    # ### end Alembic commands ###
